# Наши стейджи
stages:
  - build
  - deploy

#Билдим джаву
build-java:
  stage: build
  script:
    - cd backend
    - mvn clean install -Dmaven.test.skip
  artifacts:
    paths:
      - backend/target/*.jar
    expire_in: 30 minutes

#Билдим реакт, плюс подсовываем env
build-react:
  stage: build
  script:
    - echo "REACT_APP_API_BASE_URL=$REACT_APP_API_BASE_URL" > .env
    - unset CI
    - cd frontend
    - npm install
    - npm run build
  artifacts:
    paths:
      - frontend/build/
    expire_in: 30 minutes

#Деплоим по примеру из интернетика (ага, нет):3
deploy-all: 
  stage: deploy
  script:
    - ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_URL "systemctl --user stop uslugi.service"
    - scp -o StrictHostKeyChecking=no backend/target/practiceCSR-0.0.1-SNAPSHOT.jar $SERVER_USER@$SERVER_URL:/home/uslugi
    - ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_URL "systemctl --user start uslugi.service"
    - scp -o StrictHostKeyChecking=no -r frontend/build/** $SERVER_USER@$SERVER_URL:/var/www/html