security.jwt.token.secret-key: eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTY4ODcxMjE2MCwiaWF0IjoxNjg4NzEyMTYwfQ.fZi769njiHSDBftmMJyOeMA060OgbgnmV7JBaZtDMnQ

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/practic2023
    username: postgres
    password: 1
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
  sql:
    init:
      platform: postgres
      mode: never