security.jwt.token.secret-key: my-secret-key

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/practic2023
    username: postgres
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
  sql:
    init:
      platform: postgres
      mode: never
      data-locations: classpath:insert.sql

cors:
  allowedOrigins: 'http://172.31.100.191:4200, http://10.0.112.99, http://localhost:4200, http://localhost:3000'
  allowedMethods: 'GET, POST, PUT, DELETE'
  allowedHeaders: '*'
  allowedCredentials: false
  corsConfiguration: '/**'
  maxAge: 3600


